### ISSUE TITLE
Does the API allow reliable access to the presented video frame?

### ISSUE THREAD

**Issue by foolip** [WICG/video-rvfc#3]
https://github.com/WICG/video-raf/blob/gh-pages/explainer.md#use-cases says:
> Today sites using [WebGL](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API) or [`<canvas>`](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) with a [`<video>`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement) element rely on a set of heuristics to determine if the first frame has been presented ([video.currentTime > 0](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime), video [canplaythrough](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canplaythrough_event) event, etc). These heuristics vary across browsers. For subsequent frames sites must blindly call [Canvas.drawImage()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) or [GLContext.texImage2D()](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D) for access to the pixel data. Our proposed API would allow reliable access to the presented video frame.

However, https://wicg.github.io/video-raf/#video-frame-metadata doesn't seem to include anything that would allow access to the frame data, or any handle that could be passed to a draw command.

**Comment by tguilbert-google** [comment]
The explainer had a note saying that implementations should make sure that the video's current frame matched the one from the active callback, rather than exposing the frame or a handle to JS directly. This still meant keeping the frames alive under the hood for longer, which has some performance implications for hardware decoders.

Now that video.rAF is run as part of the "update the rendering" steps, it might take up to ~16ms between the time a callback is scheduled to be run, and actually executed. We don't want to keep a frame alive for all that extra time, and there might be newer frames that come along in the meantime. So, we are dropping the guarantee that the frame and the metadata will match.
However, when the callbacks do run, they will always pull the latest presented frame's info, which should match the current frame the majority of the time (although not guaranteed).

I will add a section to the spec about expectations/limitations/guarantees of the API.

**Comment by foolip** [comment]
Thanks for the update, sounds like these callbacks can't be used to perfectly synchronize content with the current frame, but that maybe it'll be better than any existing technique like `video.currentTime`?

**Comment by WesselKroos** [comment]
> Thanks for the update, sounds like these callbacks can't be used to perfectly synchronize content with the current frame, but that maybe it'll be better than any existing technique like `video.currentTime`?

I'm using the current implementation in the Chrome Beta. From a developer perspective I can say that this seems to be the most reliable way at this time.

- video.currentTime is unreliable if you don't know what framerate the video is playing at. And the framerate cannot be read from the video element at this moment.

- video.webkitDecodedFrameCount (webkit only, and there are some Firefox specific properties available as well with the same issues) is also unreliable at the moment because that is not in sync with the frame that is read from the video when calling canvasContext.drawImage(video). (I don't know why but it even causes missing frames on a 144hz monitor with a 24hz video.)

- Calling canvasContext.drawImage(video) on every window.requestAnimationFrame callback seems to be as in sync as calling it in every video.requestAnimationFrame callback. With the benefit of using less energy because we draw only 24 times a seconds (24hz video) instead of 144 times (144hz monitor) a second.

**Comment by tguilbert-google** [comment]
Thanks for the dev perspective Wessel! There are some significant implementation changes between the current Chrome Beta and Chrome Canary. I'm interested in hearing about your experience with the latest implementation.

The changes to run as part of the rendering steps (right before window.rAF) have landed, and here's the current state of the implementation:

We always pull the latest presented frames' information right before we run the callbacks. This means that the metadata received should always correspond to the "current frame". However, the callbacks might be run 1 rendering step after the frame was presented, which means that the pixels for that frame might already be on screen, and painting the current frame now would appear to be 1 vsync late. (This issue was already possible in the previous implementation).

We also added a heuristic to detect when the video frame rate and the browser's animation frame rate are close together (e.g. 60fps video and 60hz monitor). In that case, we can perfectly sync the content (or at least as well as requesting a paint every window.rAF), by preemptively scheduling a callback execution, instead of waiting for the presented frame signal.

**Comment by WesselKroos** [comment]
As far as I can tell I see no performance degradations only a gain for perfectly synced video's in 720p60hz  and improved synchronization for video's in 1080p60hz, both on a 60hz monitor.

Benchmarking this with the extension https://chrome.google.com/webstore/detail/youtube-ambilight/paponcgjfojgemddooebbgniglhkajkj and a video with stroboscope effects gives me these results.

Constants:
- CPU: I7 6700K
- GPU: RTX 2070
- Monitor resolution: 1440p
- Video Hz: 25
- Video: https://youtu.be/cS6Hi2Avoww?t=684

| Video res | Monitor Hz | Delay in frames (eyeballing) |
| - | - | - |
| 720p | 60 | 0 |
| 720p | 120 | 0 |
| 720p | 144 | 0, 1 (alternating) |
| 1080p | 60 | 0 |
| 1080p | 120 | 1 |
| 1080p | 144 | 2 |
| 1440p | 60 | 0, 1 (alternating) |
| 1440p | 120 | 0, 1, 2 (alternating) |
| 1440p | 144 | 1, 2 (alternating) |
| 2160p | 60 | 2 |
| 2160p | 120 | 2, 3 (alternating) |
| 2160p | 144 | 3, 4 (alternating) |

Constants:
- Monitor resolution: 1440p
- Video Hz: 60
- Video: https://youtu.be/dqlUnT0cAJ8?t=33

| Video res | Monitor Hz | Delay in frames (eyeballing) |
| - | - | - |
| 720p | 60 | 0 |
| 720p | 120 | 0, 1 (alternating) |
| 720p | 144 | 0, 1 (alternating) |
| 1080p | 60 | 0, 1 (alternating) |
| 1080p | 120 | 1 |
| 1080p | 144 | 2, 3 (alternating) |

**Comment by foolip** [comment]
I think the answer to my original question is "no", and that spelling out the lack of strict timing guarantees at the end of https://wicg.github.io/video-raf/#run-the-video-animation-frame-callbacks would make sense and would resolve this issue.

**Comment by tguilbert-google** [comment]
I have added a note in #38. I'm closing this issue for now, please re-open if needed.
