### ISSUE TITLE
Inconsistent naming of variables

### ISSUE THREAD

**Issue by tguilbert-google** [WICG/video-rvfc#42]
ElapsedProcessingTime is actually a duration, and not a time.

timePresented and expectedPresentationTime are constructed differently.

From:
https://github.com/mozilla/standards-positions/issues/250#issuecomment-600215741

**Comment by tguilbert-google** [comment]
I have an outstanding question about naming:

`presentedTime` is the only attribute that is "past tense verb + time". E.g., we currently have `captureTime` and not `capturedTime`. I'm wondering if this is an issue.

Originally, `presentedTime` was `presentationTime`, but that was too similar to `presentationTimestamp`. It would be easy for web developers to make mistakes, considering that one is a substring of the other. This is why I prefer having `presentedTime`, even if it's inconsistent.

**Comment by padenot** [comment]
It's a problem because `presented` implies it has happened, which might be true, but it's an implementation detail. I also agree with the sub-string argument, but I'd tend to prefer being explicit.

Another problem that I didn't see last time: `presentedTime` is a `DOMHiresTimestamp` (so it a timestamp in milliseconds), but `presentationTimestamp` is a double in the timeline of `HTMLMediaElement.currentTime`, in seconds.

The former is in the clock domain of the system clock, the later is a number of seconds, in the time domain of the audio output device (if the file has an audio track), or the system clock time (if not), so it's a bit backward.

Generally the later are referred to as `xxxxxxxTime`: `HTMLMediaElement.currentTime`, `AudioContext.currentTime`, `AudioWorkletGlobalScope.currentTime`, all the parameters in the `AudioParam` functions (https://webaudio.github.io/web-audio-api/#AudioParam). Then I found `Animation.currentTime`, that is in milliseconds 🙃 .

I'm thinking maybe switching the names to be closer to other media APIs would work?

**Comment by tguilbert-google** [comment]
WDYT of switching `presentationTimestamp` to `mediaTime`, and switching back `presentedTime` to `presentationTime`?

I liked `presentationTimestamp` because it is the most clear and direct naming of what the field is (the frame's PTS), but that might be coming from a media stack dev perspective, and not a web dev perspective. `mediaTime` fits other media APIs' naming, and it makes it clear that it is in the `currentTime` media domain.

> It's a problem because presented implies it has happened, which might be true, but it's an implementation detail.

IIUC, an implementer that knows ahead of time which frames they will present might not want "presented" but "presentation" instead? This way, they could still fire callbacks ahead of time, knowing the frames will be presented at the `presentationTime`?

Assuming `presentationTimestamp` is renamed to `mediaTime`:
`presentedTime` *is* a timestamp in ms, same as `expectedDisplayTime`, but I think that using `time` for a timestamp would be acceptable (window.rAF uses it for [as its callback parameter name](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#framerequestcallback)). More importantly, I don't think that renaming `presentedTime` to `presentationTimestamp` is appropriate, because it would be too confusing with media PTS. So, my proposal is `presentationTime`, which should be less problematic now that `presentationTimestamp` and `expectedPresentationTime` have been renamed.

The full list of names would therefore be:

| Name | Type | Note |
|---|---|---|
| **`presentationTime`** | `DOMHighResTimeStamp` |  |
| **`expectedDisplayTime`** | `DOMHighResTimeStamp` |  |
| `width` | `unsigned long` |  |
| `height` | `unsigned long` |  |
| **`mediaTime`** | `double` (seconds) | **~~optional~~** |
| **`processingDuration`** | `double` (seconds) | optional |
| `presentedFrames` | `unsigned long` | **~~optional~~** |
| `captureTime` | `DOMHighResTimeStamp` | optional |
| `receiveTime` | `DOMHighResTimeStamp` | optional |
| `rtpTimestamp` | `unsigned long` | optional |

(Recent or upcoming changes in bold)

**Comment by tguilbert-google** [comment]
I think this is tentatively fixed.

**Comment by tguilbert-google** [comment]
I'm closing this issue. Please re-open if necessary. The names of the attributes above will be the ones used in the M83 release of Chrome.
