### ISSUE TITLE
sync at different playback/seeking rates?

### ISSUE THREAD

**Issue by bboyle** [WICG/video-rvfc#62]
Nice API, I definitely have a use for it! We have a product that allows artists to annotate on video frames, so it's a perfect fit.

I did a test in Chrome today, and the sync felt worse than with `window.requestAnimationFrame`. I'm not sure if there is an actual performance difference, or if both lag but requestAnimationFrame fires more frequently so it has more chances to catch up and that "feels" more accurate. The metadata in this API looks very useful (and I haven't made use of it yet), I will explore that another day.

Couple of questions though. The docs talk about:

> the lesser rate between the video’s rate and the browser’s rate

I understand the playback scenario (25 fps video vs 60 Hz monitor), but:
- what if `video.playbackRate = 3` — does this callback then fire at 60 Hz (75 vs 60)?
- what if the video is paused, but there are many seek actions being triggered by updates to `video.currentTime`? Do seek actions trigger this callback? At what frequency?

Scenario: we have a scrubber control that allows animators to scrub back and forward quickly. The currentTime may be updating more than 25 times a second, although the values may not be linear — some frames may be skipped due to debouncing on the pointer events, and the user may change direction forwards/back (possibly multiple times). Hard to explain, but you can scrub some test videos here: https://bboyle.github.io/video-canvas/index.html (no annotations, but there is a linked canvas using ghosting).

**Comment by tguilbert-google** [comment]
> [...] the sync felt worse [...]

This is definitively possible. `video.rVFC` callbacks might be 1 vsync late relative to the frame appearing on screen ([detailed example here](https://github.com/WICG/video-rvfc/issues/59#issuecomment-673669352)). If the video and screen rates match (60fps video with a 60hz screen), we have an optimization to preemptively schedule the callbacks, which should remove this 1 occasional frame lag and look smoother.

> what if video.playbackRate = 3 — does this callback then fire at 60 Hz (75 vs 60)?

This API will never fire faster than the screen's refresh rate (or the `window.rAF` rate), so it would fire at 60hz.

> what if the video is paused, but there are many seek actions being triggered by updates to video.currentTime? Do seek actions trigger this callback? At what frequency?

Seeks will trigger this callback, but no faster than the refresh rate either. Assuming a 60Hz monitor with 16ms between vsyncs, if there are multiple seeks that complete within a 16 ms window, only the last one, closest to the vsync, should fire a callback.

BTW, on the linked demo, I saw that the cached frames used `Math.floor(video.currentTime * fps)` to extract frame numbers. You might get more reliable frame #s from this API's `mediaTime` (see [this comment](https://github.com/WICG/video-rvfc/issues/54#issuecomment-622021461)).

**Comment by bboyle** [comment]
Cool, thanks for that info! I was wondering if the rVFC rate could go above the video frame rate and it sounds like it totally can during seek or with a higher playbackRate — but always capped by the refresh rate (which is great, no need to paint faster than the monitor can handle in my case).

> You might get more reliable frame #s from this API's mediaTime

Interesting.

Getting an accurate frame number is quite difficult I have found. Find a page with a video, open up the developer tools and start doing things like `document.querySelector('video').currentTime = <number>` and step along like `0`, `0.000001`, `0.000002` and note the values where the rendered frame changes visibly. Take note of those numbers. Compare different browsers (like Chrome and Firefox). Is this related to audio clock vs presentationTimestamp? (I'm not familiar what those are and how they relate to video timing).

Regarding figuring out the frame number… it isn't a simple as `Math.floor(video.currentTime * fps)` (that was good enough for my demo page). I like to think that if I had a video that was 24 fps, then the first frame would span `0–0.041667` and the second frame would be `0.041668–0.083333` … in practice this seems to be false. I would _love_ an API that worked in frames rather than seconds ~:)

Is rVFC's mediaTime more accurate?

Reading the 1-frame vsync scenario… I need to spend some time understanding that. Looks useful, thanks!

**Comment by tguilbert-google** [comment]
You can think of `currentTime` based on the "audio clock" as us playing 1000 audio "frames" per second and reporting that number up. Then, we update the video frame at approximately the right time, +/- some amount of audio frames, which works fine because the audio clock's "resolution" is much finer than the video clock's "resolution" (1000 vs 30, in fps or Hz).

The `presentationTimestamp` is what you would get if you were to inspect your video file, enumerated all the frames, and looked at the actual binary time information attached to each frame, according to that file format's specifications.

So, the main advantage of rVFC's `mediaTime` is that it is deterministic. You should always get the same frame for the same `mediaTime`. Also, the number of values you can get for `mediaTime` should be much lower than the ones you can get from `currentTime` (1 per frame, as opposed to a full range of values, e.g. [2.950029, 2.952037]). So, you could cache directly on `mediaTime`, rather than calculating the frame #, or use it to calculate a deterministic frame # reliably, but there could still be hiccups due to rounding errors and how the video file is encoded.

Having an API that worked with frame numbers with the `<video>` element is unfeasible... If someone seeked to the middle of the video, we'd have to decode the entire video to guarantee we had the right frame number, because poorly encoded media might have missing frames. WebCodecs should give you enough control to do things on a frame per frame basis however.

EDIT: Removed some inaccurate info about about seeking, thanks to @dalecurtis.

**Comment by bboyle** [comment]
thanks Thomas, some great info in there. I will definitely look at `mediaTime` when I get the chance — having one value range than the full range per frame alone would be a huge win.

As for seeking into the middle of a video — you are correct. We (re)encode videos specifically with extra keys (I-Frames?) so high speed seeking is possible. Wrecks compression of course. Off to go learn about WebCodecs now…
