### ISSUE TITLE
Extracting all frames from video accurately using rvfc

### ISSUE THREAD

**Issue by lincolnneu** [WICG/video-rvfc#66]
In the demo code of https://blog.tomayac.com/2020/05/15/the-requestvideoframecallback-api/
```
const updateCanvas = (now, metadata) => {
  if (startTime === 0.0) {
    startTime = now;
  }

  ctx.drawImage(video, 0, 0, canvas.width, canvas.height);

  const elapsed = (now - startTime) / 1000.0;
  const fps = (++paintCount / elapsed).toFixed(3);
  fpsInfo.innerText = `video fps: ${fps}`;
  metadataInfo.innerText = JSON.stringify(metadata, null, 2);

  video.requestVideoFrameCallback(updateCanvas);
};

video.requestVideoFrameCallback(updateCanvas);
```

There could be 1 v-sync late between canvas and video.
But if we can eliminate 1 v-sync late using the tips in https://github.com/WICG/video-rvfc/issues/59, can we extract all frames from video accurately? We don't need the canvas to show frame in real time as the video plays. We just want to collect all the frames.

[fiddle](https://jsfiddle.net/lincolnhuj/23znkeay/15/)
```
const frameImageData = new Map();
const updateCanvas = (now, metadata) => {
  if (startTime === 0.0) {
    startTime = now;
  }
  
  // if no v-sync late, save frame image to collection. 3ms for all monitor refresh rate, including 240 Hz, 60 Hz
  if (metadata.expectedDisplayTime - now > 3 && frameImageData.get(metadata.mediaTime) == null) {
     ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
     const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
     frameImageData.set(metadata.mediaTime, imageData);
  }
 
  const elapsed = (now - startTime) / 1000.0;
  const fps = (++paintCount / elapsed).toFixed(3);
  fpsInfo.innerText = `video fps: ${fps}`;
  metadataInfo.innerText = JSON.stringify(metadata, null, 2);

  video.requestVideoFrameCallback(updateCanvas);
};

video.requestVideoFrameCallback(updateCanvas);
```

**Comment by tguilbert-google** [comment]
There is no guaranteed way to extract all frames from a video using requestVideoFrameCallback.

If you want to extract all frames accurately, you should using [WebCodecs](https://github.com/WICG/web-codecs), which you can try out in M86. WebCodecs also allows you faster than realtime capture of frames, and gives you direct access to frame data.

If you really must use video.rVFC, you could pause the video, increment the current time slowly, and wait for each seek to complete... Which is probably not very efficient, and how far you can seek depends on the encoding of the media. You could also try multiple passes to capture all frames, and seek to where you suspect you are missing frames.

Also, in your example code, you are capturing frame only when the callback is not 1 v-sync late, but if you only care about capturing frames, you don't need that check. When the callback fires, the `mediaTime` you get is guaranteed correspond to the `imageData` you are capturing. "1 v-sync late" does not mean that the callback is "1 frame late" or mismatched with the current frame. It just means the video's pixels are already on screen when the callback runs, and if you painted to a canvas then, it would be a bit off.

Again, WebCodecs is really what you are looking for.

**Comment by lincolnneu** [comment]
Is webcodecs mature enough to extract frames now? Looks like it's still under experiment and might have bugs. I prefer to stick to stable API.

**Comment by tguilbert-google** [comment]
It's stable enough that partners will start experimenting with it on real users in M86 (via an origin trial).

There will be breaking changes to the API, but probably at a lower more nuanced level. Your use case of "getting all frames" is simple enough that it should just work now.

It won't be on by default for all users until some unknown point in 2021 though.

**Comment by lincolnneu** [comment]
> and wait for each seek to complete

When rVFC is fired, the target frame is sent to compositor, but the seek (videoNode.onSeeked()) is not completed at that time? Then when will seek is completed? At the time when the frame is displayed on the monitor?

> how far you can seek depends on the encoding of the media

Which encoding is best suite for this case? We can control the video encoding. Is MP4 H.264 with all I frames good enough for this case?

We actually don't need all frames to be correct at one time. As long as the frame and metadata.mediaTime are consistent when the video is paused, other time `best effort` is OK. I did some tests, and found out that sometimes the rVFC is not fired onPause, probably because `best effort`? But since videoNode.onPause() is guaranteed, I plan to keep them consistent by `video.currentTime = metadata.mediaTime` in the onPause(). The only concern here is if this will show the correct frame consistently (https://github.com/WICG/video-rvfc/issues/64).

**Comment by lincolnneu** [comment]
>  I did some tests, and found out that sometimes the rVFC is not fired onPause, probably because best effort?

Just realize I was testing using a 120 fps video and sometimes speed up to 5x, using a 60 hz monitor. No wonder it was not fired on pause sometimes. I should limit the playback speed to be min of the monitor refresh rate and video fps.

**Comment by tguilbert-google** [comment]
>I should limit the playback speed to be min of the monitor refresh rate and video fps.

Yes. So, for 120fps video, you will need 0.5x playback speed. rVFC is not about "decoded frames", it's about "presented frames".

Otherwise, if the video is 120fps on a 60hz monitor, there might frames that are decoded but never sent to the compositor, and will never have an rVFC fired. So, `frame#1` is presented and fires an rVFC, `frame#2` is decoded an never presented, `frame#3` is presented and fires an rVFC, this would not *not* result in a discontinuity in `presentedFrames`.

`onpaused` and `onseeked` callbacks are fired as tasks, and are executed as such during the event loop, whereas video.rVFC is executed during the rendering steps. This is crucial in understanding how rVFC works ([this video is excellent at explaining the event loop differences](https://www.youtube.com/watch?v=cCOL7MC4Pl0)).

When there is a pending rVFC and there is a new frame presented ("sent to be displayed", not decoded), we schedule ourselves to be run during the next rendering steps (v-sync). During the next rendering steps, we pull the info from the *latest* presented video frame. A new frame might have been sent to the compositor since we scheduled ourselves. So, we can present `frame#1`, schedule rVFC, present `frame#2`, and run rVFC with `frame#2`. `frame#1` will never be surfaced via rVFC, and there would be a discontinuity in the `presentedFrames`.

If you have multiple seeks that complete between two rendering steps, only the last seek will produce an rVFC callback. The seeked frames in between might never be presented.

If there is a rVFC callback scheduled for the next rendering steps, and you seek, and the rendering steps happens before the `onseeked` callback is run, you might get two different frames in the rVFC:

1. The pre-seek frame that scheduled the rVFC, because the seek hasn't completed.
1. The post-seek frame, because the seek completed, but the `onseeked` callback hasn't been run.

So, if you are playing and seek to a frame, the rVFC for that specific frame might be before or after the `onseeked`. If you are paused, you may want to wait for both the rVFC and the onseeked to fire before seeking again. Otherwise, you could seek, and start a new seek from `onseeked` that completes before the next rendering steps, and the rVFC callback for the 1st seeked frame wouldn't run.

> As long as the frame and metadata.mediaTime are consistent when the video is paused

Every time you get an rVFC callback, the "imageData" you get from the video will match the `mediaTime`, even if the video is not paused.

> Sometimes the rVFC is not fired onPause, probably because best effort?

There might already have been an rVFC callback fired for the frame that is seen on screen when the video was paused.



I considered this issue closed. The answer to "can you extract all frames from a video accurately using rVFC" is no, but this thread has all of the (albeit nitty-gritty) information for those what want to try, with no guarantees.

I think a lot of this will come down to experimentation with the API and figuring out what works for your use-case. Again, [WebCodecs](https://github.com/WICG/web-codecs) seems well suited for your usecase.

**Comment by lincolnneu** [comment]
Our goal is to know the exact frame number / PTS time of frame currently displayed. The only difficulty is the uncertainty of whether rvfc is fired. 

Just come up with an idea that will give us guaranteed consistency between frame displayed on the screen and mediaTime we currently have (even if we're not sure if rVFC was fired for current frame or some rVFCs were missed due to best effort). `Only work for constant frame rate video` and we need to know FPS beforehand, but enough for my case: 

When video is paused, set video.currentTime as targetTime, and inside onSeeked, seek 1 frame back and forth around the targetTime, then check the mediaTime if `video.currentTime - mediaTime >= 0 && video.currentTime - mediaTime < 0.5 / fps`. If not, the seek will trigger another onSeeked, and do the check again and again, until video.currentTime converges with mediaTime. Just tested this method and works pretty well. It can work as a reliable way to identify frame on the screen.

**Comment by lincolnneu** [comment]
> When the callback fires, the mediaTime you get is guaranteed correspond to the imageData you are capturing.

> Every time you get an rVFC callback, the "imageData" you get from the video will match the mediaTime, even if the video is not paused.

Are these statements only true when video frame rate <= monitor refresh rate? I get this using the [fiddle](https://jsfiddle.net/lincolnhuj/23znkeay/20/) after removing the vsync late check. 

The video is 120 fps and I played it at 1 x speed, monitor 60Hz. Image data of frame 375 was mistakenly captured as PTS 3.116667(should be PTS of 374) while video is playing. You can reproduce it simply by playing and pausing several times (may happen to other frames).

![image](https://user-images.githubusercontent.com/39422558/95041391-69ca0480-068b-11eb-920f-12837e82f170.png)

This is very confusing since the getImageData is within rVFC, and it should match the PTS/mediaTime all the time.

**Comment by tguilbert-google** [comment]
Actually, what I said about the guarantee of the metadata and the frame matching was wrong, and I apologize for that. You are right about video.rVFC and higher frame rate videos not having the corresponding PTS matching the frame.

At some point during video.rVFC's development, we had that guarantee, but had to drop it for technical reasons. In practice, it wasn't a problem, even though there was a risk of that happening due to threading issues. It appears that it's more likely in higher frame rate videos, when there is more of a chance that the underlying frame would be updated during the course of the rVFC callback.

After WebCodecs ships, there is a plan to update video.rVFC to give you back the frame directly, which would circumvent the issue. This is blocked on WebCodecs because it defines the web VideoFrame type.

**Comment by lincolnneu** [comment]
I'll limit the playback rate that (video playback rate) * fps < monitor refresh rate. It's guaranteed that video frame matches mediaTime in this condition, right? Guaranteed matching PTS time to video frame is the only reason that I use rVFC.

**Comment by tguilbert-google** [comment]
> It's guaranteed that video frame matches mediaTime in this condition, right?

No :/ That was my mistake. The latest frame can internally be updated on the compositor thread after we read its metadata, so there might be a mismatch. It's less likely to happen if your video playback rate is lower (e.g. 30fps on a 60hz), but it could always happen technically.

**Comment by lincolnneu** [comment]
How about we pause and seek video once at a time, and wait until a metadata.presentationTime from rVFC be later than the seek time using https://github.com/WICG/video-rvfc/issues/67 ? I assume one seek will only trigger 1 frame sent to compositor, and so the read then change situation will not exist in this case.

**Comment by lincolnneu** [comment]
> The latest frame can internally be updated on the compositor thread after we read its metadata, so there might be a mismatch.

Makes sense. The rVFC can guarantee metadata matches the frame at the exact time when rVFC is fired, but no guarantee the compositor thread will wait for callback inside rVFC to finish before processing the next frame. (And this is why rVFC is best effort and may miss some rVFC calls for some frames). So it may not be accurate to cache frame using rVFC while video is playing.

But the metadata from rVFC is still valuable to know which frame we're at. If we can make sure there's no new video frame is processed after a known rVFC call (e.g. no new seek), the PTS time from last known rVFC can tell us which frame the video player is showing, I guess.

**Comment by tguilbert-google** [comment]
> I assume one seek will only trigger 1 frame sent to compositor, and so the read then change situation will not exist in this case.

The seek should indeed trigger only 1 frame update... But there are some internal ways in which the video element may still cause a frame udpate. We queue a frame update internally after every time there is a "direct" access to the current frame (e.g. when painting to a canvas) to manually drive frame updates, in the offscreen WebGL case.

If the video is paused and there are no seeks happening, I think this *should* be ok, because the paused clock should prevent the current frame from being considered stale. I don't know for sure that this is always true, especially for high frame rate videos. Maybe one could check if this is a problem by having a paused video, painting it to a canvas in window.rAF loop, then seeking here and there, and seeing if there is ever a second rVFC call for a given seek...

**Comment by lincolnneu** [comment]
Even though 1 seek might trigger multiple frame update, we perform the `metadata.presentationTime > seek time` check in onSeeked event. onSeeked will guarantee there's no more frame sent to compositor. (If not, it's not `seeked` yet, and means there's a bug in the browser)

**Comment by tguilbert-google** [comment]
For reference, here's is a demo of using WebCodecs to extract all frames from an mp4 file:
https://tguilbert-google.github.io/webcodecs/mp4/index.html

**Comment by lincolnneu** [comment]
> The latest frame can internally be updated on the compositor thread after we read its metadata, so there might be a mismatch.

What will the frame internally be updated to when the video is paused/onSeeked event is fired? A frame with a different PTS timestamp? Say at the time when we get a rVFC callback right before the video is paused, metadata.mediaTime=1.0 s, metadata.expectedDisplayTime=T and the frame displayed is frame A. After a series of internal update, finally the frame is updated to frame B. When I check the screen at time T or after T (video is paused and no other seek), are we sure that it's showing frame B and frame B's PTS timestamp is 1.0s?

**Comment by tguilbert-google** [comment]
I think there is the possible edge case

If you are not yet paused, and you pause, the following could theoretically happen:
rVFC callback start on main thread with metadata from Frame A
Frame A is updated to Frame B on compositor thread
Access Frame B from rVFC callback on main thread
Requeue rVFC request from callback
End of rVFC callback

Since the video is paused, there will be no frame C to trigger the rVFC, and you would have PTS A for frame B

If you are paused, and you waited enough for the internal state to stabilize, and then you seek, I'm assuming that the rVFC callback should give you metadata matching the frame (and that you could copy the data from the video from the rVFC callback at that point, without waiting for the pixels to show up on screen OR you can wait until the expected display time).

I think to the best of my knowledge this is true, but it's so nitty-gritty and hypothetical that it's hard to reason about with certainty, as I might have overlooked something.

rVFC will likely give you VideoFrames directly once WebCodec ships.

**Comment by lincolnneu** [comment]
> If you are paused, and you waited enough for the internal state to stabilize, and then you seek

We can wait for long enough, since we actually don't need to capture the imageData (we use `<video/>`) for render.
As long as we are sure that the pts time I get from rvfc when one seek after pause matches the eventual video frame after stabilization, that's enough.

BTW, looks like the webcodecs will be shipped after mid next year and we can't wait for that long :)
