### ISSUE TITLE
Unstable callback calls

### ISSUE THREAD

**Issue by Pryanishnik** [WICG/video-rvfc#77]
Hello everyone, hope for your help!
I'm woking on real time video processing that requires stable 30 FPS.
This part of requirements is covered, BUT what I figured out is that rVFC calls are inconsistent in time. For video with 30 FPS it's expected to get rVFC approximately every ~34 ms or about it. What I see is that -  yes, in second there are about 30 triggerings of rVFC, but some of them are triggered with interval in 5-7 ms, some of them are called actually in a row (like <1ms interval).
In this case a lot of frames in second are literally duplicates, and a lot of 30 unique frames are missed. Is that a known issue or I do something wrong?

Basic usage:

```
async storeFrame(){
        if(!this.first){
            this.first = true;
        }

        if(!this.#isRunning){
            return;
        }
        let now = Date.now();
        if (this.startTime === 0.0) {
            this.startTime = now;
        }

        const elapsed = (now - this.startTime) / 1000.0;
        const fps = (this.paintCount++ / elapsed).toFixed(3);
        if(isDevEnv){
            document.getElementById("fpsInfo").innerText = `video fps: ${fps}`;
        }

        let ctx = this.#canvas.getContext('2d');
        ctx.drawImage(this.#src, 0,0);
        //let image = ctx.getImageData(0,0, this.#canvas.width, this.#canvas.height);
        let img = await createImageBitmap(this.#canvas);

   
        this.#buffer.push(img);
    
        this.#src.requestVideoFrameCallback(this.storeFrame.bind(this));
    }
```

**Comment by tguilbert-google** [comment]
The fact that some of them are called in a row is surprising.

What happens if you log the contents of the metadata? E.g:

```
async storeFrame(now, metadata) {
  ...
  console.log(metadata.presentationTime)
  ...
}
```

**Comment by Pryanishnik** [comment]
![image](https://user-images.githubusercontent.com/43049295/125435065-ba507430-a5fd-4be6-a658-d1514e776113.png)
I don't see the described numbers before, but I made a video with stopwatch on it, and frames, that are actually grabbed, are incorrect.
Show example below. There are 4 consecutive frames, so difference in time should be 30+ms
![image](https://user-images.githubusercontent.com/43049295/125435362-2c23b1cc-72be-4a79-ab93-755d22c5473c.png)
![image](https://user-images.githubusercontent.com/43049295/125435632-d3df2dde-bfef-4db9-ab0e-9b6b8cbdf826.png)
![image](https://user-images.githubusercontent.com/43049295/125435675-26e2049a-b26d-4f0f-bb95-7d4ad6f5fcd8.png)
![image](https://user-images.githubusercontent.com/43049295/125435468-7d8d22fc-4863-4e1f-9e94-0f0e4bbb72a6.png)

**Comment by tguilbert-google** [comment]
Ok. What I see from the printed out `presentationTime` is that there are no duplicates from the rVFC callback's POV. In other words, things seem to be working correctly for rVFC itself.

I would recommend trying your code with a AV sync test video (for [example here](https://www.youtube.com/watch?v=ucZl6vQ_8Uo)) that is known to have proper encoding. You should otherwise confirm that all the frames in your source video are unique, using ffmpeg ([example command](https://stackoverflow.com/questions/10957412/fastest-way-to-extract-frames-using-ffmpeg)) to examine its content frame by frame.

That being said, rVFC operates on a best effort basis, and there are still cases you can run into that would result in duplicate images, despite a well encoded source video. Take this code for example:

```
function captureTwoFrames(now, metadata) {
  let frameA = createImageBitmap(this.#src);
  ...
  let frameB = createImageBitmap(this.#src);
  ...
  this.#src.requestVideoFrameCallback(this.captureTwoFrames.bind(this));
}
```

`frameA` and `frameB` could be different because, under the hood, the compositor thread might update the underlying `<video>`'s frame, while `captureTwoFrames()` is running on the main thread.


If you need exact frame guarantees, I suggest that you look at [WebCodecs](https://github.com/w3c/webcodecs), which might be better suited for certain applications.

**Comment by Pryanishnik** [comment]
Yes, that's true, I also took a look at webcodecs, but aren't they too much experimental now?:) Browser flag or tokens are hard to use in production, or is there any way to use them without flags/tokens?

**Comment by tguilbert-google** [comment]
WebCodecs should be available in M93 or M94.

**Comment by tguilbert-google** [comment]
FYI, WebCodecs has shipped.
