### ISSUE TITLE
The 'presentedFrames' field does adjust to seeking in a video

### ISSUE THREAD

**Issue by jpdiogoNOVA** [WICG/video-rvfc#82]
Hello everyone!

I have a piece of code that works as something like this:

```js
let arg1 = (...);
const callFrameByFrame= (now, metadata) => {
    myFunction(arg1, metadata.presentedFrames);
    video.requestVideoFrameCallback(callFrameByFrame);
};
video.requestVideoFrameCallback(callFrameByFrame);
```

The function `myFunction` works fine throughout the video being played even if this piece of code only begins executing X seconds after the video has begun (ex: 5 seconds after the video has started). However, this `video` element is associated with a slider where it is possible to move to a specific time (<ins>targetTime</ins>) in a video by doing something like:

```js
video.currentTime = targetTime;
```

The problem is after doing this, `myFunction` no longer receives the `metadata.presentedFrames` equal to the current frame in that video's current second which makes it run out of sync with the video when seeking.

Has anyone found a way to work around this?

Kinds regards,
Joao Diogo,
Nova University

**Comment by tguilbert-google** [comment]
The fact that `presentedFrames` does not update after seeks is by design. `presendtedFrames` corresponds to the number of frames sent to the compositor, regardless of where those frames came from in the video/stream.

I do not know if there is a way to work around this, and depends on how `presentedFrames` is being used by `myFunction`. Depending on your needs, you could use [WebCodecs](https://w3c.github.io/webcodecs/) to extract all frames manually.

**Comment by jpdiogoNOVA** [comment]
Thank you!

That's the same conclusion we arrived at.

Kinds regards,
Joao Diogo,
Nova University

**Comment by tguilbert-google** [comment]
Sounds good!
