### ISSUE TITLE
rvfc behavior when the <video/> node loads an audio only .mp4?

### ISSUE THREAD

**Issue by lincolnneu** [WICG/video-rvfc#91]
Hey video-rvfc team, we recently notice chrome run into "Aw Snap Error code:11" when playing the audio only "video" .mp4 file when requestVideoFrameCallback is turned on for the video node.

Should we avoid using video-rvfc for audio only video? What's the behavior of requestVideoFrameCallback when the "video" is audio only?

**Comment by tguilbert-google** [comment]
I would expect that rVFC is never called, if there is no video track. This seems like an implementation bug rather than a specification issue.

Please open a new issue at https://issues.chromium.org/new (sharing the bug number here would be useful too), and we will investigate there. Please share said "video" if possible, or a minimized repro case. Thanks!
